# configuration for "master" branch
- 
  branches:
    only:
      - master
  image: Visual Studio 2017
  platform: Any CPU
  configuration: Release
  build_script:
  - ps: ./build.ps1 Build
  test_script:
  - ps: ./build.ps1 CreateNuget
  artifacts:
  - path: build/nuget/*.nupkg
    name: nuget
  deploy:
    provider: NuGet
    api_key:
      secure: HasnovdVw/qO3yQPSPdHZwC2GOg5KJVvT8eAwAxuW2wUTgr5lgOdZJNc46RTZ4ng
    skip_symbols: false
    artifact: /.*\.nupkg/

# configuration for all branches starting from "dev"
- 
  branches:
    only:
      - dev
  image: Visual Studio 2017
  platform: Any CPU
  configuration: Release
  build_script:
  - ps: ./build.ps1 Build
  test_script:
  - ps: ./build.ps1 CreateNuget
  artifacts:
  - path: build/nuget/*.nupkg
    name: nuget
  deploy:
    provider: NuGet
    server: https://www.myget.org/F/akkadotnet-contrib/api/v2/package
    api_key:
      secure: yoMgcchmDuXbvT90bgrUTOUNYgAId6QI0nofIOtnlfWzMjDEWfOqNqqTGPY+02M+
    skip_symbols: false
    symbol_server: https://www.myget.org/F/akkadotnet-contrib/symbols/api/v2/package
    artifact: /.*\.nupkg/